/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as IniciarSesionRouteImport } from './routes/iniciar-sesion'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AlumnoRouteImport } from './routes/alumno'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as AlumnoIndexRouteImport } from './routes/alumno.index'
import { Route as DemoConfiguracionRouteImport } from './routes/demo.configuracion'
import { Route as DemoChatRouteImport } from './routes/demo.chat'
import { Route as DemoBandejaRouteImport } from './routes/demo.bandeja'
import { Route as AlumnoPerfilRouteImport } from './routes/alumno.perfil'
import { Route as AlumnoNutricionRouteImport } from './routes/alumno.nutricion'
import { Route as AlumnoEntrenamientoRouteImport } from './routes/alumno.entrenamiento'
import { Route as AlumnoChatRouteImport } from './routes/alumno.chat'
import { Route as DemoAlumnosIndexRouteImport } from './routes/demo.alumnos.index'
import { Route as DemoAlumnosNuevoRouteImport } from './routes/demo.alumnos.nuevo'
import { Route as DemoAlumnosIdRouteImport } from './routes/demo.alumnos.$id'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciarSesionRoute = IniciarSesionRouteImport.update({
  id: '/iniciar-sesion',
  path: '/iniciar-sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumnoRoute = AlumnoRouteImport.update({
  id: '/alumno',
  path: '/alumno',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const AlumnoIndexRoute = AlumnoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlumnoRoute,
} as any)
const DemoConfiguracionRoute = DemoConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => DemoRoute,
} as any)
const DemoChatRoute = DemoChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DemoRoute,
} as any)
const DemoBandejaRoute = DemoBandejaRouteImport.update({
  id: '/bandeja',
  path: '/bandeja',
  getParentRoute: () => DemoRoute,
} as any)
const AlumnoPerfilRoute = AlumnoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AlumnoRoute,
} as any)
const AlumnoNutricionRoute = AlumnoNutricionRouteImport.update({
  id: '/nutricion',
  path: '/nutricion',
  getParentRoute: () => AlumnoRoute,
} as any)
const AlumnoEntrenamientoRoute = AlumnoEntrenamientoRouteImport.update({
  id: '/entrenamiento',
  path: '/entrenamiento',
  getParentRoute: () => AlumnoRoute,
} as any)
const AlumnoChatRoute = AlumnoChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AlumnoRoute,
} as any)
const DemoAlumnosIndexRoute = DemoAlumnosIndexRouteImport.update({
  id: '/alumnos/',
  path: '/alumnos/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAlumnosNuevoRoute = DemoAlumnosNuevoRouteImport.update({
  id: '/alumnos/nuevo',
  path: '/alumnos/nuevo',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAlumnosIdRoute = DemoAlumnosIdRouteImport.update({
  id: '/alumnos/$id',
  path: '/alumnos/$id',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alumno': typeof AlumnoRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registro': typeof RegistroRoute
  '/alumno/chat': typeof AlumnoChatRoute
  '/alumno/entrenamiento': typeof AlumnoEntrenamientoRoute
  '/alumno/nutricion': typeof AlumnoNutricionRoute
  '/alumno/perfil': typeof AlumnoPerfilRoute
  '/demo/bandeja': typeof DemoBandejaRoute
  '/demo/chat': typeof DemoChatRoute
  '/demo/configuracion': typeof DemoConfiguracionRoute
  '/alumno/': typeof AlumnoIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/alumnos/$id': typeof DemoAlumnosIdRoute
  '/demo/alumnos/nuevo': typeof DemoAlumnosNuevoRoute
  '/demo/alumnos/': typeof DemoAlumnosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registro': typeof RegistroRoute
  '/alumno/chat': typeof AlumnoChatRoute
  '/alumno/entrenamiento': typeof AlumnoEntrenamientoRoute
  '/alumno/nutricion': typeof AlumnoNutricionRoute
  '/alumno/perfil': typeof AlumnoPerfilRoute
  '/demo/bandeja': typeof DemoBandejaRoute
  '/demo/chat': typeof DemoChatRoute
  '/demo/configuracion': typeof DemoConfiguracionRoute
  '/alumno': typeof AlumnoIndexRoute
  '/demo': typeof DemoIndexRoute
  '/demo/alumnos/$id': typeof DemoAlumnosIdRoute
  '/demo/alumnos/nuevo': typeof DemoAlumnosNuevoRoute
  '/demo/alumnos': typeof DemoAlumnosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alumno': typeof AlumnoRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registro': typeof RegistroRoute
  '/alumno/chat': typeof AlumnoChatRoute
  '/alumno/entrenamiento': typeof AlumnoEntrenamientoRoute
  '/alumno/nutricion': typeof AlumnoNutricionRoute
  '/alumno/perfil': typeof AlumnoPerfilRoute
  '/demo/bandeja': typeof DemoBandejaRoute
  '/demo/chat': typeof DemoChatRoute
  '/demo/configuracion': typeof DemoConfiguracionRoute
  '/alumno/': typeof AlumnoIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/alumnos/$id': typeof DemoAlumnosIdRoute
  '/demo/alumnos/nuevo': typeof DemoAlumnosNuevoRoute
  '/demo/alumnos/': typeof DemoAlumnosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alumno'
    | '/demo'
    | '/iniciar-sesion'
    | '/registro'
    | '/alumno/chat'
    | '/alumno/entrenamiento'
    | '/alumno/nutricion'
    | '/alumno/perfil'
    | '/demo/bandeja'
    | '/demo/chat'
    | '/demo/configuracion'
    | '/alumno/'
    | '/demo/'
    | '/demo/alumnos/$id'
    | '/demo/alumnos/nuevo'
    | '/demo/alumnos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/iniciar-sesion'
    | '/registro'
    | '/alumno/chat'
    | '/alumno/entrenamiento'
    | '/alumno/nutricion'
    | '/alumno/perfil'
    | '/demo/bandeja'
    | '/demo/chat'
    | '/demo/configuracion'
    | '/alumno'
    | '/demo'
    | '/demo/alumnos/$id'
    | '/demo/alumnos/nuevo'
    | '/demo/alumnos'
  id:
    | '__root__'
    | '/'
    | '/alumno'
    | '/demo'
    | '/iniciar-sesion'
    | '/registro'
    | '/alumno/chat'
    | '/alumno/entrenamiento'
    | '/alumno/nutricion'
    | '/alumno/perfil'
    | '/demo/bandeja'
    | '/demo/chat'
    | '/demo/configuracion'
    | '/alumno/'
    | '/demo/'
    | '/demo/alumnos/$id'
    | '/demo/alumnos/nuevo'
    | '/demo/alumnos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlumnoRoute: typeof AlumnoRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  IniciarSesionRoute: typeof IniciarSesionRoute
  RegistroRoute: typeof RegistroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciar-sesion': {
      id: '/iniciar-sesion'
      path: '/iniciar-sesion'
      fullPath: '/iniciar-sesion'
      preLoaderRoute: typeof IniciarSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumno': {
      id: '/alumno'
      path: '/alumno'
      fullPath: '/alumno'
      preLoaderRoute: typeof AlumnoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/alumno/': {
      id: '/alumno/'
      path: '/'
      fullPath: '/alumno/'
      preLoaderRoute: typeof AlumnoIndexRouteImport
      parentRoute: typeof AlumnoRoute
    }
    '/demo/configuracion': {
      id: '/demo/configuracion'
      path: '/configuracion'
      fullPath: '/demo/configuracion'
      preLoaderRoute: typeof DemoConfiguracionRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/chat': {
      id: '/demo/chat'
      path: '/chat'
      fullPath: '/demo/chat'
      preLoaderRoute: typeof DemoChatRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/bandeja': {
      id: '/demo/bandeja'
      path: '/bandeja'
      fullPath: '/demo/bandeja'
      preLoaderRoute: typeof DemoBandejaRouteImport
      parentRoute: typeof DemoRoute
    }
    '/alumno/perfil': {
      id: '/alumno/perfil'
      path: '/perfil'
      fullPath: '/alumno/perfil'
      preLoaderRoute: typeof AlumnoPerfilRouteImport
      parentRoute: typeof AlumnoRoute
    }
    '/alumno/nutricion': {
      id: '/alumno/nutricion'
      path: '/nutricion'
      fullPath: '/alumno/nutricion'
      preLoaderRoute: typeof AlumnoNutricionRouteImport
      parentRoute: typeof AlumnoRoute
    }
    '/alumno/entrenamiento': {
      id: '/alumno/entrenamiento'
      path: '/entrenamiento'
      fullPath: '/alumno/entrenamiento'
      preLoaderRoute: typeof AlumnoEntrenamientoRouteImport
      parentRoute: typeof AlumnoRoute
    }
    '/alumno/chat': {
      id: '/alumno/chat'
      path: '/chat'
      fullPath: '/alumno/chat'
      preLoaderRoute: typeof AlumnoChatRouteImport
      parentRoute: typeof AlumnoRoute
    }
    '/demo/alumnos/': {
      id: '/demo/alumnos/'
      path: '/alumnos'
      fullPath: '/demo/alumnos/'
      preLoaderRoute: typeof DemoAlumnosIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/alumnos/nuevo': {
      id: '/demo/alumnos/nuevo'
      path: '/alumnos/nuevo'
      fullPath: '/demo/alumnos/nuevo'
      preLoaderRoute: typeof DemoAlumnosNuevoRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/alumnos/$id': {
      id: '/demo/alumnos/$id'
      path: '/alumnos/$id'
      fullPath: '/demo/alumnos/$id'
      preLoaderRoute: typeof DemoAlumnosIdRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface AlumnoRouteChildren {
  AlumnoChatRoute: typeof AlumnoChatRoute
  AlumnoEntrenamientoRoute: typeof AlumnoEntrenamientoRoute
  AlumnoNutricionRoute: typeof AlumnoNutricionRoute
  AlumnoPerfilRoute: typeof AlumnoPerfilRoute
  AlumnoIndexRoute: typeof AlumnoIndexRoute
}

const AlumnoRouteChildren: AlumnoRouteChildren = {
  AlumnoChatRoute: AlumnoChatRoute,
  AlumnoEntrenamientoRoute: AlumnoEntrenamientoRoute,
  AlumnoNutricionRoute: AlumnoNutricionRoute,
  AlumnoPerfilRoute: AlumnoPerfilRoute,
  AlumnoIndexRoute: AlumnoIndexRoute,
}

const AlumnoRouteWithChildren =
  AlumnoRoute._addFileChildren(AlumnoRouteChildren)

interface DemoRouteChildren {
  DemoBandejaRoute: typeof DemoBandejaRoute
  DemoChatRoute: typeof DemoChatRoute
  DemoConfiguracionRoute: typeof DemoConfiguracionRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoAlumnosIdRoute: typeof DemoAlumnosIdRoute
  DemoAlumnosNuevoRoute: typeof DemoAlumnosNuevoRoute
  DemoAlumnosIndexRoute: typeof DemoAlumnosIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoBandejaRoute: DemoBandejaRoute,
  DemoChatRoute: DemoChatRoute,
  DemoConfiguracionRoute: DemoConfiguracionRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoAlumnosIdRoute: DemoAlumnosIdRoute,
  DemoAlumnosNuevoRoute: DemoAlumnosNuevoRoute,
  DemoAlumnosIndexRoute: DemoAlumnosIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlumnoRoute: AlumnoRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  IniciarSesionRoute: IniciarSesionRoute,
  RegistroRoute: RegistroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
